---

- block:
    - name: firefox_versions | Report version
      debug:
        msg: >-
          {{ "Installing firefox version: '" + cur_firefox.version
              + "' with language '" + cur_firefox.lang + "'"
          }}
    - name: firefox_versions | Create install directory
      file:
        path:   "{{ cur_firefox.dir }}"
        mode:   0755
        state:  directory
    - name: firefox_versions | Download
      get_url:
        url:  "{{ cur_firefox.url }}"
        dest: "{{ user_dist_dir + '/' + cur_firefox.archive }}"
        force:  "{{ force_overwrite }}"
      register: cur_firefox_download
    - name: firefox_versions | Unpack
      unarchive:
        src:      "{{ user_dist_dir + '/' + cur_firefox.archive }}"
        dest:     "{{ cur_firefox.dir }}"
        remote_src: yes
        creates: >-
          {{ ( force_overwrite or cur_firefox_download.changed )
              | ternary(file_does_not_exist, cur_firefox.bin)
          }}
    - name: firefox_versions | Create symlink to firefox binary
      file:
        path:   "{{ ansible_user_dir + '/bin/' + cur_firefox.desktop | splitext | first }}"
        state:  link
        src:    "{{ cur_firefox.bin }}"
    - name: firefox_versions | Copy desktop entry
      template:
        src:    'firefox/firefox.desktop'
        dest:   "{{ user_desktop_entries + '/' + cur_firefox.desktop }}"
        force:  yes
        backup: yes

