---

# `python-apt` required for `apt` and `package_facts` ansible modules.
- block:
    - name: Check required python-apt package
      apt:
        name: 'python-apt'
        state: present
      ignore_errors: yes
      register: apt_status
    - name: Install python-apt packages
      apt:
        name: python-apt
        state: present
      when: apt_status.failed
      become: yes

- block:
    - name: Obtain package status
      package_facts:
        manager: apt

    - name: Debug
      set_fact:
        install_im_pkgs: "{{ install_im_pkgs + [item] }}"
      when: ansible_facts.packages[item] is not defined
      loop: "{{ required_im_pkgs }}"
    - name: Install required packages
      apt:
        name: "{{ install_im_pkgs }}"
        state: present
      when: install_im_pkgs | length > 0
      become: yes

      #    - name: Install im packages
      #      apt:
      #        name: "{{ item }}"
      #        state: present
      #      become: yes
      #      when: item in pkg_status
      #      loop: "{{ required_im_pkgs }}"

- block:
    - name: Install IM config
      template:
        src:    "xinputrc"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.xinputrc"
    # FIXME: Several ibus options are required for xkb config to work (if ibus
    # is running). Particularly, `use-system-keyboard-layout`..
    - name: Set up ibus config in dconf
      dconf:
        key: "{{ '/desktop/ibus/' + item.key }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ ibus_dconf }}"
  tags:
    - 'im_config'

