---

# This tasks may be used as pre-tasks in main play.

- name: load_pre | Merge desktop colors
  ansible.builtin.set_fact:
    colors: >
      {{ {item.key : all_colors | default(item.value)} | combine(colors) }}
  loop: "{{ desktop_colors | dict2items }}"

- name: load_pre | Loaded desktop colors are..
  ansible.builtin.debug:
    var: colors

