---

# This tasks may be used as pre-tasks in main play.

- name: load | Merge desktop colors
  set_fact:
    colors: >
      {{ {item.key : all_colors | default(item.value)} | combine(colors) }}
  with_dict: "{{ desktop_colors }}"

- name: load | Loaded desktop colors are..
  debug:
    var: colors
