---

- name: load | Include OS-specific vars file
  ansible.builtin.include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ role_path }}/vars/empty.yml"
