---

- block:
    - name: Load pre_tasks
      ansible.builtin.import_tasks: load_pre.yml

    - name: Load
      ansible.builtin.import_tasks: load.yml
  tags:
    - 'always'

- name: Create user dist directory exists
  ansible.builtin.file:
    path: "{{ user_dist_dir }}"
    state: directory
  tags:
    - 'always'

- name: Configure xkb layout
  ansible.builtin.include_tasks:
    file: xkb.yml
    apply:
      tags:
        - 'xkb'
  when: _xkb_mods
  tags:
    - 'xkb'

- name: Install IM config
  ansible.builtin.import_tasks: im.yml
  tags:
    - 'im'

- block:
    - name: Install parcellite
      ansible.builtin.package:
        name: parcellite
        state: present
      become: yes
      when: _internet_available and ansible_facts.packages['parcellite'] is not defined
    - name: Install parcellite config
      ansible.builtin.copy:
        src:    "parcellite/parcelliterc"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.config/parcellite/"
  tags:
    - 'copy_paste'

- block:
    - name: Create X resources directory
      ansible.builtin.file:
        state:  directory
        dest:   "{{ user_x_resources }}"
    - name: Install X resources
      ansible.builtin.template:
        src:    "{{ item }}"
        dest:   "{{ user_x_resources + '/' + item | basename }}"
        force:  yes
      with_fileglob:
        - "templates/Xresources/*.res"
    # FIXME: This color setup require further setup vim setup. Particularly, it
    # requires vim solarized plugin to be installed.
    - name: Assemble X resources
      ansible.builtin.assemble:
        src:    "{{ user_x_resources }}"
        backup: yes
        dest:   "{{ ansible_user_dir }}/.Xresources"
  tags:
    - 'colors'
    - 'colors_config'

- name: Install xmonad
  ansible.builtin.import_tasks: xmonad.yml
  tags:
    - 'xmonad'
    - 'gui'

- name: Install desktop packages
  ansible.builtin.import_tasks: gui.yml
  tags:
    - 'gui'

- block:
    - name: Firefox fixes
      ansible.builtin.import_tasks: firefox.yml
  tags:
    - 'firefox'

- name: Install anki
  ansible.builtin.import_tasks: anki.yml
  when: ansible_distribution_major_version | int == 9
  tags:
    - 'anki'

