---

- name: Load
  import_tasks: load.yml
  tags:
    - 'load'
    - 'colors'
    - 'colors_config'
    - 'debug'

# `python-apt` required for `apt` and `package_facts` ansible modules.
- block:
    - name: Check required python-apt package
      apt:
        name: 'python-apt'
        state: present
      ignore_errors: yes
      register: apt_status
    - name: Install python-apt package
      apt:
        name: python-apt
        state: present
      when: apt_status.failed
      become: yes
  tags:
    - 'debug'

- name: Configure xkb layout
  import_tasks: xkb.yml
  when: xkb_mods
  tags:
    - 'xkb'

- name: Install IM config
  import_tasks: im.yml
  tags:
    - 'im'

- name: Install parcellite config
  copy:
    src:    "parcellite/parcelliterc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.config/parcellite/"
  tags:
    - 'copy_paste'

- block:
    - name: Create X resources directory
      file:
        state:  directory
        dest:   "{{ user_x_resources }}"
    - name: Install X resources
      template:
        src:    "{{ item }}"
        dest:   "{{ user_x_resources + '/' + item | basename }}"
        force:  yes
      with_fileglob:
        - "templates/Xresources/*.res"
    # FIXME: This color setup require further setup vim setup. Particularly, it
    # requires vim solarized plugin to be installed.
    - name: Assemble X resources
      assemble:
        src:    "{{ user_x_resources }}"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.Xresources"
  tags:
    - 'colors'
    - 'colors_config'


- block:
    - name: Obtain package status
      package_facts:
        manager: apt

    - name: Build list of xmonad dependencies to install
      set_fact:
        xmonad_install_pkgs: "{{ xmonad_install_pkgs + [item] }}"
      when: ansible_facts.packages[item] is not defined
      loop: "{{ xmonad_required_pkgs }}"
    - name: Install xmonad deps
      debug:
        var: xmonad_install_pkgs
    - name: Install required packages
      apt:
        name: "{{ xmonad_install_pkgs }}"
        state: present
      when: xmonad_install_pkgs | length > 0
      become: yes
  tags:
    - 'debug'

- block:
    - name: Clone xmonad
      git:
        repo: 'https://github.com/sgf-dma/sgf-xmonad-config.git'
        dest: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"
        version: "{{ xmonad_branch }}"
        clone: yes
      register: xmonad_updated

    - name: Build xmonad
      make:
        chdir: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"
        target: install
      when: xmonad_bin is not exists or xmonad_updated.changed
  tags:
    - 'xmonad'

