---

- block:
    - name: Load
      import_tasks: load.yml
  tags:
    - 'always'

- name: Configure xkb layout
  include_tasks: xkb.yml
  when: xkb_mods
  tags:
    - 'xkb'

- name: Install IM config
  import_tasks: im.yml
  tags:
    - 'im'

- block:
    - name: Install parcellite
      apt:
        name: parcellite
        state: present
      become: yes
      when: ansible_facts.packages['parcellite'] is not defined
    - name: Install parcellite config
      copy:
        src:    "parcellite/parcelliterc"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.config/parcellite/"
  tags:
    - 'copy_paste'

- block:
    - name: Create X resources directory
      file:
        state:  directory
        dest:   "{{ user_x_resources }}"
    - name: Install X resources
      template:
        src:    "{{ item }}"
        dest:   "{{ user_x_resources + '/' + item | basename }}"
        force:  yes
      with_fileglob:
        - "templates/Xresources/*.res"
    # FIXME: This color setup require further setup vim setup. Particularly, it
    # requires vim solarized plugin to be installed.
    - name: Assemble X resources
      assemble:
        src:    "{{ user_x_resources }}"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.Xresources"
  tags:
    - 'colors'
    - 'colors_config'

- name: Install xmonad
  import_tasks: xmonad.yml
  tags:
    - 'xmonad'
    - 'gui'

- name: Install desktop packages
  import_tasks: gui.yml
  tags:
    - 'gui'

- block:
    - name: Firefox fixes
      import_tasks: firefox.yml
  tags:
    - 'firefox'

- name: Install anki
  import_tasks: anki.yml
  when: ansible_distribution_major_version | int == 9
  tags:
    - 'anki'

