---

- name: Configure xkb layout
  import_tasks: xkb.yml
  tags:
    - 'xkb'

- name: Install parcellite config
  copy:
    src:    "parcellite/parcelliterc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.config/parcellite/"
  tags:
    - 'copy_paste'

- name: Install IM config
  copy:
    src:    "xinputrc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.xinputrc"
  tags:
    - 'im'

- name: Assemble X resources
  assemble:
    src:    "{{ role_path }}/files/Xresources"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.Xresources"
  tags:
    - 'colors'

- block:
    - name: Install xmonad
      git:
        repo: 'https://github.com/sgf-dma/sgf-xmonad-config.git'
        dest: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"
        version: master
        clone: yes
      register: xmonad_updated

    - name: Build xmonad
      make:
        chdir: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"
        target: install
      when: xmonad_bin is not exists or xmonad_updated.changed
  tags:
    - 'xmonad'

