---

- block:
    - name: Load
      import_tasks: load.yml

    # `python-apt` required for `apt` and `package_facts` ansible modules.
    - name: Check required python-apt package
      apt:
        name: 'python-apt'
        state: present
      ignore_errors: yes
      register: apt_status
    - name: Install python-apt package
      apt:
        name: python-apt
        state: present
      when: apt_status.failed
      become: yes

    - name: Obtain package status
      package_facts:
        manager: apt
  tags:
    - 'load'
    - 'colors'
    - 'colors_config'
    - 'xkb'
    - 'im'
    - 'xmonad'
    - 'deps'
    - 'debug'

- name: Configure xkb layout
  import_tasks: xkb.yml
  when: xkb_mods
  tags:
    - 'xkb'

- name: Install IM config
  import_tasks: im.yml
  tags:
    - 'im'

- name: Install parcellite config
  copy:
    src:    "parcellite/parcelliterc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.config/parcellite/"
  tags:
    - 'copy_paste'

- block:
    - name: Create X resources directory
      file:
        state:  directory
        dest:   "{{ user_x_resources }}"
    - name: Install X resources
      template:
        src:    "{{ item }}"
        dest:   "{{ user_x_resources + '/' + item | basename }}"
        force:  yes
      with_fileglob:
        - "templates/Xresources/*.res"
    # FIXME: This color setup require further setup vim setup. Particularly, it
    # requires vim solarized plugin to be installed.
    - name: Assemble X resources
      assemble:
        src:    "{{ user_x_resources }}"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.Xresources"
  tags:
    - 'colors'
    - 'colors_config'

- name: Install xmonad
  import_tasks: xmonad.yml
  tags:
    - 'xmonad'

