---

- block:
    - name: xmonad | Define dependencies
      ansible.builtin.set_fact:
        xmonad_install_pkgs: "{{ xmonad_install_pkgs + [item] }}"
      when: ansible_facts.packages[item] is not defined
      loop: "{{ xmonad_required_pkgs }}"

    - name: xmonad | Show xmonad dependencies to be installed
      ansible.builtin.debug:
        var: xmonad_install_pkgs
  tags:
    - 'load'
    - 'xmonad_deps'

- name: xmonad | Install xmonad dependencies
  ansible.builtin.package:
    name: "{{ xmonad_install_pkgs }}"
    state: present
  when: _internet_available and xmonad_install_pkgs | length > 0
  become: yes
  tags:
    - 'xmonad_deps'

- block:
    - name: xmonad | Get stack installer
      ansible.builtin.get_url:
        url:  'https://get.haskellstack.org/'
        dest: "{{ haskell_stack_installer }}"
        mode: '0750'

    - name: xmonad | Run stack installer
      ansible.builtin.command: "{{ haskell_stack_installer }} -d {{ haskell_stack_bin_path }} -f"
      args:
        creates: "{{ haskell_stack_bin_path + '/stack' }}"

  when: _internet_available
  tags:
    - 'xmonad_deps'

- block:
    - name: xmonad | Clone repository
      ansible.builtin.git:
        repo: 'https://github.com/sgf-dma/sgf-xmonad-config.git'
        dest: "{{ xmonad_repo_dir }}"
        version: "{{ xmonad_branch }}"
        clone: yes
      register: xmonad_updated

    - name: xmonad | Determine xmobar repo path
      ansible.builtin.command:
        argv:
          - /bin/readlink
          - '-f'
          - "{{ xmonad_repo_dir + '/extra-pkgs/xmobar' }}"
      register: xmobar_repo_readlink
      changed_when: false
      check_mode: false

    - name: xmonad | Clone xmobar repository
      ansible.builtin.git:
        repo: 'https://github.com/jaor/xmobar.git'
        dest: "{{ xmobar_repo_readlink.stdout }}"
        version: "{{ xmobar_branch }}"
        clone: yes
      register: xmobar_updated

  when: _internet_available
  tags:
    - xmonad_bin

- block:
    - name: xmonad | Stat binary
      ansible.builtin.stat:
        path: "{{ xmonad_bin }}"
      register: xmonad_bin_stats

    - name: xmonad | Stat xmobar binary
      ansible.builtin.stat:
        path: "{{ xmobar_bin }}"
      register: xmobar_bin_stats

    - name: xmonad | Build
      community.general.make:
        chdir: "{{ xmonad_repo_dir }}"
        target: install
      when: not ( xmonad_bin_stats.stat.exists and xmobar_bin_stats.stat.exists )
            or  ( xmonad_updated.changed or xmobar_updated.changed )
            or  _force_overwrite

  tags:
    - xmonad_bin

- block:
    # User's Xsession.d normally is created by xmonad Makefile, but just to be
    # sure..
    - name: xmonad | Create user's Xsession.d directory
      ansible.builtin.file:
        path:   "{{ user_xsession_dir }}"
        mode:   0755
        state:  directory

    - name: xmonad | Add user's bin to PATH in Xsession
      ansible.builtin.copy:
        src:    "{{ item }}"
        force:  yes
        backup: yes
        dest:   "{{ user_xsession_dir + '/' + item | basename }}"
      loop: "{{ lookup('fileglob', 'files/Xsession/*', wantlist=True) }}"

  tags:
    - xmonad_xsession

