---

- block:
    - name: xmonad | Define dependencies
      set_fact:
        xmonad_install_pkgs: "{{ xmonad_install_pkgs + [item] }}"
      when: ansible_facts.packages[item] is not defined
      loop: "{{ xmonad_required_pkgs }}"
    - name: xmonad | Show xmonad dependencies to be installed
      debug:
        var: xmonad_install_pkgs
  tags:
    - 'load'
    - 'xmonad_deps'

- name: xmonad | Install xmonad dependencies
  apt:
    name: "{{ xmonad_install_pkgs }}"
    state: present
  when: xmonad_install_pkgs | length > 0
  become: yes
  tags:
    - 'xmonad_deps'

- block:
    - name: xmonad | Get stack installer
      get_url:
        url:  'https://get.haskellstack.org/'
        dest: "{{ haskell_stack_installer }}"
        mode: '0750'
    - name: xmonad | Run stack installer
      command: "{{ haskell_stack_installer }} -d {{ haskell_stack_bin_path }} -f"
      args:
        creates: "{{ haskell_stack_bin_path + '/stack' }}"
  tags:
    - 'xmonad_deps'

- block:
    - name: xmonad | Clone repository
      git:
        repo: 'https://github.com/sgf-dma/sgf-xmonad-config.git'
        dest: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"
        version: "{{ xmonad_branch }}"
        clone: yes
      register: xmonad_updated

    - name: xmonad | Stat binary
      stat:
        path: "{{ xmonad_bin }}"
      register: xmonad_bin_stats
    - name: xmonad | Build
      make:
        chdir: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"
        target: install
      when: not xmonad_bin_stats.stat.exists or xmonad_updated.changed

