---

- name: Configure home directory
  hosts: all:localhost
  vars:
    all_colors: 'solarized-dark'
    firefox52esr_lang: 'ru'
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: sgf.dma@gmail.com
        git_name: sgf
      tags:
        - 'console'
    - role: sgf-desktop
      vars:
        firefox_default_desktop: 'firefox-52.9.0esr.desktop'
        firefox_versions:
          - version: '52.9.0esr'
            profile: 'default-52esr'
            comment: 'Firefox 52 ESR'
      tags:
        - 'desktop'

