---

- name: Configure home directory
  hosts: all:localhost
  vars:
    all_colors: 'solarized-dark'
    notebook: true
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: sgf.dma@gmail.com
        git_name: sgf
      tags:
        - 'console'

    - role: sgf-desktop
      tags:
        - 'desktop'
    - role: sgf-system
      tags:
        - 'system'

    - role: pdns_recursor-ansible
      vars:
        pdns_rec_config_lua_file_content: >
          rpzFile("/etc/powerdns/rpz.db", {})
        pdns_rec_config:
          allow-from:
            - "127.0.0.1/8"
          local-address:
            - "127.0.0.1"
          pdns-distributes-queries: false
          reuseport: true
      tags:
        - 'system'

