---

- name: Configure home directory
  hosts: all:localhost
  vars:
    all_colors: 'solarized-dark'
    notebook: true
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      tags:
        - 'console'

    - role: sgf-desktop
      tags:
        - 'desktop'

    - role: sgf-system
      vars:
        my_pdns_rec_config:
          network-timeout: 5000
          packetcache-servfail-ttl: 5
        grub_drives: { 'windows': {'uuid': 'dce80401-5870-49e5-9c75-797723c51fcc'} }
        grub_menus:
          { 'load_os':
              { 'crypt_uuid': '2ee2542c68ad429785af3482300da27d'
              , 'root_drive': '(lvmid/tihzUI-hh3j-wMvd-CE82-oTGg-iscO-fHGEcx/m2Yakg-mWch-cFt4-Mipx-TExf-sfhi-xpLZr2)'
              }
          , 'windows': {}
          , 'truecrypt_rescue': {}
          }
        interface_links:
          { '00:c0:ca:b0:62:de' : {'name': 'alfaAcm1'}
          , '84:16:f9:12:8f:a9' : {'name' : 'tplink1'}
          , '0c:5b:8f:27:9a:64' : {'name' : 'huawei'}
          }
      tags:
        - 'system'

