---

- name: Configure home directory
  hosts: all:localhost
  vars:
    all_colors: 'solarized-dark'
    notebook: true
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: sgf.dma@gmail.com
        git_name: sgf
        dns_forwarder: '127.0.2.1:53'
      tags:
        - 'console'

    - role: sgf-desktop
      vars:
        xmobar_branch: e71512b7c961ab379aee98c2f4d65ad4bdd3c5bf
        firefox_default_desktop: 'firefox-esr.desktop'
        firefox_versions:
          - version: '52.9.0esr'
            profile: 'default-52esr'
            comment: 'Firefox 52 ESR'
          - version: 'latest'
      tags:
        - 'desktop'

    - role: sgf-system
      vars:
        my_pdns_rec_config:
          network-timeout: 5000
          packetcache-servfail-ttl: 5
        grub_drives: { 'windows': {'uuid': 'dce80401-5870-49e5-9c75-797723c51fcc'} }
        grub_menus:
          { 'load_os':
              { 'crypt_uuid': '2ee2542c68ad429785af3482300da27d'
              , 'root_drive': '(lvmid/tihzUI-hh3j-wMvd-CE82-oTGg-iscO-fHGEcx/m2Yakg-mWch-cFt4-Mipx-TExf-sfhi-xpLZr2)'
              }
          , 'windows': {}
          , 'truecrypt_rescue': {}
          }
      tags:
        - 'system'

