---

- name: Configure home directory
  hosts: all:localhost
  vars:
    all_colors: 'solarized-dark'
    notebook: true
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: sgf.dma@gmail.com
        git_name: sgf
        dns_forwarder: '127.0.2.1:53'
      tags:
        - 'console'

    - role: sgf-desktop
      tags:
        - 'desktop'

    - role: sgf-system
      vars:
        my_pdns_rec_config:
          network-timeout: 5000
      tags:
        - 'system'

