---

- name: Configure home directory
  hosts: all:localhost
  vars:
    all_colors: 'solarized-dark'
    notebook: true
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: sgf.dma@gmail.com
        git_name: sgf
        dns_forwarder: '127.0.2.1:53'
      tags:
        - 'console'

    - role: sgf-desktop
      vars:
        xmobar_branch: e71512b7c961ab379aee98c2f4d65ad4bdd3c5bf
        firefox_default_desktop: 'firefox-esr.desktop'
        firefox_versions:
          - version: '52.9.0esr'
            profile: 'default-52esr'
            comment: 'Firefox 52 ESR'
          - version: 'latest'
      tags:
        - 'desktop'

    - role: sgf-system
      vars:
        my_pdns_rec_config:
          network-timeout: 5000
          packetcache-servfail-ttl: 5
      tags:
        - 'system'

