---

- name: Configure home directory
  hosts: all:localhost
  vars:
    colors:
      tmux: 'dark-domovoy'
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: domovoy@bh-desktop
        git_name: domovoy
        vim_disable_arrow_keys: false
        tmux_prefix: 'C-a'
        tmux_prefix_key: 'a'
      tags:
        - 'console'
    - role: sgf-desktop
      vars:
        xmobar_branch: ca5b802bd4fa134cdbc3e4986d64b5116bcffd68
        xmonad_branch: domovoy-master
        firefox_default_desktop: 'firefox-latest.desktop'
        firefox_system_profile: 'default-esr'
        xkb_clear_options: false
        im_enabled: false
        firefox_versions:
          - version: '52.9.0esr'
            profile: 'default-52esr'
            comment: 'Firefox 52 ESR'
          - version: 'latest'
            profile: 'default'
      tags:
        - 'desktop'

