---

- name: Install xkb configs
  hosts: localhost
  pre_tasks:
    - name: Merge colors
      import_tasks: load.yml
  roles:
    - role: sgf-console
      vars:
        git_email: sgf.dma@gmail.com
        git_name: sgf
        colors:
          hui: nahui
    - role: sgf-desktop

