---

- name: Configure home directory
  hosts: all:localhost
  vars:
    colors:
      tmux: 'dark-domovoy'
  pre_tasks:
    - name: Load variables
      import_tasks: load.yml
      tags:
        - 'always'
  roles:
    - role: sgf-console
      vars:
        git_email: domovoy@bh-desktop
        git_name: domovoy
        vim_disable_arrow_keys: false
        tmux_prefix: 'C-a'
        tmux_prefix_key: 'a'
      tags:
        - 'console'
    - role: sgf-desktop
      vars:
        xkb_clear_options: false
        im_enabled: false
        xmonad_branch: domovoy-master
      tags:
        - 'desktop'

