---

- name: Install xkb configs
  hosts: localhost
  roles:
    - role: sgf-desktop
      vars:
        xkb_clear_options: false
        im_enabled: false
        xmonad_branch: domovoy-master
        xterm_solarized: disabled
    - role: sgf-console
      vars:
        git_email: domovoy@bh-desktop
        git_name: domovoy
        vim_disable_arrow_keys: false
        tmux_prefix: 'C-a'
        vim_solarized: disabled
        tmux_solarized: disabled


