
source ~/.vimrc_common

{% if vim_plugins_enable %}
execute pathogen#infect()
{% endif %}

{% if colors.vim != 'disabled' %}

{#- `colors.xterm` is defined in `sgf-desktop` role -#}
{% if colors.xterm == 'disabled' %}

{% raw %}" Degrade to 256 colros.
{% endraw %}
let g:solarized_termcolors=256
set background={{ colors.vim | replace ('solarized-', '', 1) }}

{% else %}

{#- Vim backgrounds change their meaning, when terminal _also_ uses solarized
colorscheme: `dark` now means use solarized colorscheme _matching_ with
terminal, and `light` means use solarized colorscheme _inverse_ to your
terminal. -#}
{% if colors.vim == colors.xterm %}
set background=dark
{% else %}
set background=light
{% endif %}

{% endif %}

let g:solarized_diffmode="high"

colorscheme solarized
{% endif %}

let g:table_mode_corner_corner='+'
let g:table_mode_header_fillchar='='
let g:vim_markdown_no_extensions_in_markdown = 1

{% if _vim_disable_arrow_keys %}
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

{% endif %}
