
source ~/.vimrc_common

execute pathogen#infect()

{% if colors.vim != 'disabled' %}

{#- `colors.xterm` is defined in `sgf-desktop` role -#}
{% if colors.xterm == 'disabled' %}
{% raw %}" Degrade to 256 colros.
{% endraw %}
let g:solarized_termcolors=256
{% endif %}

{% if colors.vim == 'solarized-dark' %}
set background=dark
{% elif colors.vim == 'solarized-light' %}
set background=light
{% endif %}

let g:solarized_diffmode="high"

colorscheme solarized
{% endif %}

let g:table_mode_corner_corner='+'
let g:table_mode_header_fillchar='='
let g:vim_markdown_no_extensions_in_markdown = 1

{% if vim_disable_arrow_keys %}
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

{% endif %}
