---
# defaults file for roles/sgf-system

# If PC is notebook, i usually want to disable wake on lan, because it'll
# drain battery even in hibernate. This is global setting, which will be
# applied _only_ to ethernet interfaces. Ethernet interfaces are correctly
# recognized _only_, if they use new naming scheme (starting with `en`).
# Alternatively, i may overwrite guessed value below.
disable_wol: "{{ _sys_notebook | ternary(true, false) }}"

# To force some options on particular interface, i may overwrite guessed
# values. For now, this is useful only for forcing disabling wake on lan on
# some interfaces.
interface_links: {}

# Address of DNS forwarder. Usually, this should be dnscrypt proxy.
#dns_forwarder: '127.0.2.1:53'

tmp_on_tmpfs: yes

# Overwrite for `pdns_rec_config` .
my_pdns_rec_config: {}

# key - grub drive name, which will be used to generate grub functions for
# finding this drive and may be used in 'grub_menus' dictionary to refer to
# this drive.
# Values:
# 'uuid' - uuid of fs on grub partition for particular drive. This will be
# used to identify that drive and to install grub into that drive. Implicitly,
# this requires, that boot (grub) partitions were _not_ in raid (i.e. all fs
# uuids are different).
# 'device' - explicit device path.
# 'no_grub' - do not install grub on this drive.
grub_drives: {}

# key - must be one of keys defined in 'grub_menus_all' (from
# 'vars/main.yml').
# Values:
# all values of corresponding key (from 'grub_menus_all') may be redefined
# here. To use default values, just define empty dictionary value for that
# key. Only menuentries corresponding to keys _defined here_ will be
# generated.
grub_menus: {}

