---
# defaults file for roles/sgf-system

# If PC is notebook, i usually want to disable wake on lan, because it'll
# drain battery even in hibernate. This is global setting, which will be
# applied _only_ to ethernet interfaces. Ethernet interfaces are correctly
# recognized _only_, if they use new naming scheme (starting with `en`).
# Alternatively, i may overwrite guessed value below.
disable_wol: "{{ _sys_notebook | ternary(true, false) }}"

# To force some options on particular interface, i may overwrite guessed
# values. For now, this is useful only for forcing disabling wake on lan on
# some interfaces.
interface_links: {}

# Address of DNS forwarder. Usually, this should be dnscrypt proxy.
#dns_forwarder: '127.0.2.1:53'

tmp_on_tmpfs: yes

# Overwrite for `pdns_rec_config` .
my_pdns_rec_config: {}

grub_menus:
  { 'load_os' :
      { 'crypt_uuid' : '2ee2542c68ad429785af3482300da27d'
      , 'root_drive' : '(lvmid/tihzUI-hh3j-wMvd-CE82-oTGg-iscO-fHGEcx/m2Yakg-mWch-cFt4-Mipx-TExf-sfhi-xpLZr2)'
      }
  }

grub_drives:
  { 'windows' : {'uuid' : 'dce80401-5870-49e5-9c75-797723c51fcc'}
  }

