---

# This tasks may be used as pre-tasks in main play.

- name: load_pre | Merge console colors
  set_fact:
    colors: >
      {{ {item.key : all_colors | default(item.value)} | combine(colors) }}
  loop: "{{ console_colors | dict2items }}"

- name: load_pre | Loaded console colors are..
  debug:
    var: colors

