---
# tasks file for sgf-tmux

- name: Load pre_tasks
  import_tasks: load_pre.yml
  tags:
    - 'always'

- block:
    - name: shell | Ensure user local path exists
      file:
        path: "{{ user_local_path }}"
        state: directory

    - name: shell | Ensure user man1 directory exists
      file:
        path: "{{ user_man1_path }}"
        state: directory

  tags:
    - always

- block:
    - name: Install git
      package:
        name: 'git'
        state: present
      become: yes
      when: ansible_facts.packages['git'] is not defined
    - name: Install git config
      template:
        src:    "gitconfig"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.gitconfig"
  tags:
    - 'tmux'
    - 'vim'
    - 'git'

- block:
    - name: Install tmux
      package:
        name: 'tmux'
        state: present
      become: yes
      when: ansible_facts.packages['tmux'] is not defined
    - name: Install common tmux config
      include_tasks:
        file: tmux.yml
        apply:
          tags:
            - 'tmux'
            - 'colors'
  when: tmux_enable
  tags:
    - 'tmux'
    - 'colors'

- block:
    - name: Configure bashrc
      include_tasks:
        file: shell.yml
        apply:
          tags:
            - 'shell'
  tags:
    - 'shell'

- block:
    - name: Install vim
      package:
        name: 'vim'
        state: present
      become: yes
      when: ansible_facts.packages['vim'] is not defined
    - name: Configure vim
      include_tasks:
        file: vim.yml
        apply:
          tags:
            - 'vim'
            - 'colors'
  when: vim_enable
  tags:
    - 'vim'
    - 'colors'

