---
# tasks file for sgf-tmux

- name: Install common tmux config
  import_tasks: tmux.yml
  tags:
    - 'tmux'

- name: Install git config
  template:
    src:    "gitconfig"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.gitconfig"
  tags:
    - 'git'

- name: Modifications to .bashrc
  blockinfile:
    path:   "{{ ansible_user_dir + '/.bashrc' }}"
    backup: yes
    insertafter: EOF
    block: |
      export LANG=en_US.utf8
      export LC_CTYPE=ru_RU.utf8
      export LC_COLLATE=ru_RU.utf8
      export PATH="$HOME/bin:$PATH"
      umask 027

      eval $(thefuck --alias)
      eval $(keychain --eval id_rsa)
  tags:
    - 'shell'

- name: Configure vim
  import_tasks: vim.yml
  tags:
    - 'vim'

