---
# tasks file for sgf-tmux

- name: Install common tmux config
  template:
    src:    "tmux-common.conf"
    force:  yes
    dest:   "{{ ansible_user_dir }}/.tmux-common.conf"

- name: Install parcellite config
  copy:
    src:    "parcellite/parcelliterc"
    force:  yes
    dest:   "{{ ansible_user_dir }}/.config/parcellite/"

