---
# tasks file for sgf-tmux

- name: Install common tmux config
  template:
    src:    "tmux-common.conf"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.tmux-common.conf"

- name: Install parcellite config
  copy:
    src:    "parcellite/parcelliterc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.config/parcellite/"

- name: Install git config
  template:
    src:    "gitconfig"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.gitconfig"

- name: Install IM config
  copy:
    src:    "xinputrc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.xinputrc"

- name: Assemble X resources
  assemble:
    src:    "{{ role_path }}/files/Xresources"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.Xresources"

- name: Modifications to .bashrc
  blockinfile:
    path:   "{{ ansible_user_dir + '/.bashrc' }}"
    backup: yes
    insertafter: EOF
    block: |
      export LANG=en_US.utf8
      export LC_CTYPE=ru_RU.utf8
      export LC_COLLATE=ru_RU.utf8
      export PATH="$HOME/bin:$PATH"
      umask 027

      eval $(thefuck --alias)
      eval $(keychain --eval id_rsa)

