---
# tasks file for sgf-tmux

- name: Load pre_tasks
  import_tasks: load_pre.yml
  tags:
    - 'always'

- block:
    - name: Install git
      apt:
        name: 'git'
        state: present
      become: yes
      when: ansible_facts.packages['git'] is not defined
    - name: Install git config
      template:
        src:    "gitconfig"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.gitconfig"
  tags:
    - 'tmux'
    - 'vim'
    - 'git'

- block:
    - name: Install tmux
      apt:
        name: 'tmux'
        state: present
      become: yes
      when: ansible_facts.packages['tmux'] is not defined
    - name: Install common tmux config
      include_tasks:
        file: tmux.yml
        apply:
          tags:
            - 'tmux'
            - 'colors'
  when: tmux_enable
  tags:
    - 'tmux'
    - 'colors'

- block:
    - name: Install bashrc dependencies
      apt:
        name: keychain
        state: present
      become: yes
      when: ansible_facts.packages['keychain'] is not defined
    - name: Modifications to .bashrc
      blockinfile:
        path:   "{{ ansible_user_dir + '/.bashrc' }}"
        backup: yes
        marker: '# {mark} desktop-config ANSIBLE MANAGED BLOCK'
        insertafter: EOF
        block: |-

            # Include common settings.
            . ~/.bashrc-common

    - name: Install common bashrc
      template:
        src:    'bashrc'
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir + '/.bashrc-common' }}"


  tags:
    - 'shell'

- block:
    - name: Install vim
      apt:
        name: 'vim'
        state: present
      become: yes
      when: ansible_facts.packages['vim'] is not defined
    - name: Configure vim
      include_tasks:
        file: vim.yml
        apply:
          tags:
            - 'vim'
            - 'colors'
  when: vim_enable
  tags:
    - 'vim'
    - 'colors'

