---
# tasks file for sgf-tmux

- name: Load
  import_tasks: load.yml
  tags:
    - 'always'

- block:
    - name: Install git
      apt:
        name: 'git'
        state: present
      become: yes
      when: ansible_facts.packages['git'] is not defined
    - name: Install git config
      template:
        src:    "gitconfig"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.gitconfig"
  tags:
    - 'tmux'
    - 'vim'
    - 'git'

- block:
    - name: Install tmux
      apt:
        name: 'tmux'
        state: present
      become: yes
      when: ansible_facts.packages['tmux'] is not defined
    - name: Install common tmux config
      import_tasks: tmux.yml
  when: tmux_enable
  tags:
    - 'tmux'
    - 'colors'

- block:
    - name: Install bashrc dependencies
      apt:
        name: keychain
        state: present
      become: yes
      when: ansible_facts.packages['keychain'] is not defined
    - name: Modifications to .bashrc
      blockinfile:
        path:   "{{ ansible_user_dir + '/.bashrc' }}"
        backup: yes
        insertafter: EOF
        block: "{{ lookup('file', 'files/bashrc') }}"
  tags:
    - 'shell'

- block:
    - name: Install vim
      apt:
        name: 'vim'
        state: present
      become: yes
      when: ansible_facts.packages['vim'] is not defined
    - name: Configure vim
      import_tasks: vim.yml
  when: vim_enable
  tags:
    - 'vim'
    - 'colors'

