---
# tasks file for sgf-tmux

- name: Load pre_tasks
  import_tasks: load_pre.yml
  tags:
    - 'always'

- block:
    - name: shell | Ensure user local path exists
      file:
        path: "{{ user_local_path }}"
        state: directory

    - name: shell | Stat user local bin
      stat:
        path: "{{ user_local_bin }}"
      register: user_local_bin_stats

    - name: shell | Stat user bin
      stat:
        path: "{{ user_bin }}"
      register: user_bin_stats

    - block:
        - name: shell | Remove ~/.local/bin symlink to ~/bin
          file:
            path: "{{ user_local_bin }}"
            state: absent
          when: >-
            user_local_bin_stats.stat.islnk is defined
            and user_local_bin_stats.stat.islnk
            and user_local_bin_stats.stat.lnk_source == ansible_user_dir + '/bin'

        - name: shell | Move ~/bin, if exists, to ~/.local/bin
          command:
            argv:
              - mv
              - '-T'
              - "{{ user_bin }}"
              - "{{ user_local_bin }}"
          args:
            creates: "{{ user_local_bin }}"
            removes: "{{ user_bin }}"
          when: user_bin_stats.stat.isdir is defined and user_bin_stats.stat.isdir

        - name: shell | Ensure user local bin exists
          file:
            path: "{{ user_local_path + '/bin' }}"
            force: no
            follow: no
            state: directory

        - name: shell | Ensure, that ~/bin was not symlink to wrong target
          assert:
            that:
              - not user_bin_stats.stat.exists
                or  user_bin_stats.stat.exists
                    and (   user_bin_stats.stat.islnk
                            and user_bin_stats.stat.lnk_source == user_local_bin
                        or  not user_bin_stats.stat.islnk
                        )
            msg: "It seems, that ~/bin is already a symlink, but not to ~/.local/bin"

        - name: shell | Create ~/bin as symlink to ~/.local/bin
          file:
            path: "{{ user_bin }}"
            follow: yes
            state: link
            src:  "{{ user_local_bin }}"

    - name: shell | Ensure user man1 directory exists
      file:
        path: "{{ user_man1_path }}"
        state: directory

    - name: shell | Ensure user bash_completion directory exists
      file:
        path: "{{ user_bash_completion_dir }}"
        state: directory

  tags:
    - always
    - pathes

- block:
    - name: Install git
      package:
        name: 'git'
        state: present
      become: yes
      when: ansible_facts.packages['git'] is not defined
    - name: Install git config
      template:
        src:    "gitconfig"
        force:  yes
        backup: yes
        dest:   "{{ ansible_user_dir }}/.gitconfig"
  tags:
    - 'tmux'
    - 'vim'
    - 'git'

- block:
    - name: Install tmux
      package:
        name: 'tmux'
        state: present
      become: yes
      when: ansible_facts.packages['tmux'] is not defined
    - name: Install common tmux config
      include_tasks:
        file: tmux.yml
        apply:
          tags:
            - 'tmux'
            - 'colors'
  when: tmux_enable
  tags:
    - 'tmux'
    - 'colors'

- block:
    - name: Configure bashrc
      import_tasks: shell.yml
  tags:
    - 'shell'

- block:
    - name: Install vim
      package:
        name: 'vim'
        state: present
      become: yes
      when: ansible_facts.packages['vim'] is not defined
    - name: Configure vim
      include_tasks:
        file: vim.yml
        apply:
          tags:
            - 'vim'
            - 'colors'
  when: vim_enable
  tags:
    - 'vim'
    - 'colors'

