---

- name: tmux | Install common config
  template:
    src:    "tmux-common.conf"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.tmux-common.conf"
  tags:
    - 'colors_config'

- name: tmux | Install main config
  copy:
    src:    "files/tmux.conf"
    force:  no
    dest:   "{{ tmux_conf }}"

- block:
    - name: tmux | Install tpm
      git:
        repo:   'https://github.com/tmux-plugins/tpm'
        clone:  yes
        dest:   "{{ tmux_plugin_dir + '/tpm' }}"
    - name: tmux | Add tpm run to tmux.conf
      lineinfile:
        dest:   "{{ tmux_conf }}"
        insertafter: EOF
        backup: yes
        state:  present
        # FIXME: Hardcoded `tmux_plugin_dir` .
        line:   "run '~/.tmux/plugins/tpm/tpm'"
  when: internet_available | bool

- block:
    - name: tmux | Install solarized colors plugin
      git:
        repo:   'https://github.com/seebi/tmux-colors-solarized'
        clone:  yes
        dest:   "{{ tmux_plugin_dir + '/tmux-colors-solarized' }}"
      when: internet_available | bool

    - name: tmux | Copy additional colorschemes
      copy:
        src:    "{{ item }}"
        dest:   "{{ tmux_plugin_dir + '/tmux-colors-solarized' }}"
      with_fileglob:
        - "tmux-colors/*"
      tags:
        - 'colors_config'

  when: colors.tmux != 'disabled'

