---

- name: Install common tmux config
  template:
    src:    "tmux-common.conf"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir }}/.tmux-common.conf"

- name: Install main tmux config
  copy:
    src:    "files/tmux.conf"
    force:  no
    dest:   "{{ tmux_conf }}"

- block:
    - name: Install tpm
      git:
        repo:   'https://github.com/tmux-plugins/tpm'
        clone:  yes
        dest:   "{{ tmux_plugin_dir + '/tpm' }}"
    - name: Add tpm run to tmux.conf
      lineinfile:
        dest:   "{{ tmux_conf }}"
        insertafter: EOF
        backup: yes
        state:  present
        # FIXME: Hardcoded `tmux_plugin_dir` .
        line:   "run '~/.tmux/plugins/tpm/tpm'"

- name: Install solarized colors
  git:
    repo:   'https://github.com/seebi/tmux-colors-solarized'
    clone:  yes
    dest:   "{{ tmux_plugin_dir + '/tmux-colors-solarized' }}"
  when: tmux_solarized != 'disabled'

