---

- name: vim | Create directories
  file:
    path:   "{{ vim_dir + item }}"
    state:  directory
  loop:
    - '/autoload'
    - '/bundle'

- name: vim | Install pathogen
  get_url:
    url:  'https://tpo.pe/pathogen.vim'
    dest: "{{ vim_dir + '/autoload/pathogen.vim' }}"
  when: _internet_available

# FIXME: `.vimrc` references some plugins, which may not be there..
- name: vim | Intall common vimrc
  copy:
    src:    "{{ item }}"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir + '/.' + item | basename }}"
  with_fileglob:
    - "vim/vimrc*"
  tags:
    - 'vim_config'

- name: vim | Intall main vimrc
  template:
    src:    "vim/vimrc"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir + '/.vimrc' }}"
  tags:
    - 'vim_config'
    - 'colors_config'

- name: vim | Checkout plugins
  git:
    repo: "{{ item.repo }}"
    # Note, yaml block chomping indicator to remove trailing newline.
    dest: >-
      {{ vim_package_dir + '/'
          + item.dest | default(item.repo | basename | splitext | first)
      }}
    clone: yes
  loop: "{{ vim_plugins }}"
  when: _internet_available

