---

- block:
    - name: vim | Create directories
      ansible.builtin.file:
        path:   "{{ vim_dir + item }}"
        state:  directory
      loop:
        - '/autoload'
        - '/bundle'

  when: _vim_plugins_enable

- block:
    - name: vim | Install pathogen
      ansible.builtin.get_url:
        url:  'https://tpo.pe/pathogen.vim'
        dest: "{{ vim_dir + '/autoload/pathogen.vim' }}"
      when: _internet_available

    - name: vim | Checkout plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        # Note, yaml block chomping indicator to remove trailing newline.
        dest: >-
          {{ vim_package_dir + '/'
              + item.dest | default(item.repo | basename | splitext | first)
          }}
        clone: yes
      loop: "{{ vim_plugins }}"

  when: _vim_plugins_enable and _internet_available

- name: vim | Copy vim config files
  ansible.builtin.copy:
    src:    "{{ item }}"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir + '/.' + item | basename }}"
  with_fileglob:
    - "vim/vimrc*"
  tags:
    - 'vim_config'

- name: vim | Generate vim configs
  ansible.builtin.template:
    src:    "{{ item }}"
    force:  yes
    backup: yes
    dest:   "{{ ansible_user_dir + '/.' + item | basename }}"
  with_fileglob:
    - "vim/*"
  tags:
    - 'vim_config'
    - 'colors_config'

