---
# handlers file for roles/sgf-system

- name: reload systemd
  systemd:
    daemon-reload: yes
  become: yes

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  become: yes
