---

- block:
    # Wireless interfaces may have generated mac address different from real
    # hardware mac. I need to use real hardware macaddress in link files to
    # match.
    - name: Stat wireless phy macaddress file
      stat:
        path: "{{ '/sys/class/net/' + item + '/phy80211/macaddress' }}"
      register: macaddress_stats
      loop: "{{ ansible_facts['interfaces'] }}"
    - name: Obtain phy macaddresses
      slurp:
        src: "{{ item.stat.path }}"
      register: phy_macaddress_content
      when: item.stat.exists
      loop: "{{ macaddress_stats.results }}"
    - name: Define interfaces
      set_fact:
        _interface_links: >
          {{  [ { 'name'        : item.0
                , 'file'        : '/etc/systemd/network/50-' + item.0 + '.link'
                , 'disable_wol' : disable_wol
                                  and ( item.0[0:2] == 'en' or item.0[0:3] == 'eth' )
                , 'phy_macaddress' : item.1.content | default('') | b64decode | trim
                      | default(ansible_facts[item.0]['macaddress'], true)
                } | combine(interface_links[item.0] | default({}))
              ] + _interface_links
          }}
      when: ansible_facts[item.0]['macaddress'] is defined
      loop: "{{ ansible_facts['interfaces'] | zip(phy_macaddress_content.results) | list }}"
    - name: Show interfaces
      debug:
        var: _interface_links

- block:
    # To disable `mac` naming policy and random mac address for interfaces
    # connected through usb (applyed in
    # `/lib/udev/rules.d/73-usb-net-by-mac.rules`) i may create this symlink
    # (see `TEST` in that file for other ways to avoid). After that link files
    # will apply.
    - name: Disable udev rule forcing mac naming policy for usb interfaces
      file:
        src:  '/lib/udev/rules.d/80-net-setup-link.rules'
        path: '/etc/udev/rules.d/80-net-setup-link.rules'
        state: link
        force: no
      become: yes
      when: ansible_distribution == "Debian"
            and ansible_distribution_major_version | int == 9

    # Template expects variable `interface` containing interface name.
    - name: Generate per-interface link file based on default.link
      template:
        src:  'interface.link'
        dest: "{{ item.file }}"
        force: no
        mode:   0644
        owner:  'root'
        group:  'root'
      vars:
        interface: "{{ item }}"
      loop: "{{ _interface_links }}"
      become: yes
      notify:
        - reload systemd

    - name: Disable wake on lan
      lineinfile:
        dest: "{{ item.file }}"
        backup: yes
        line: 'WakeOnLan=off'
        regexp: "(^#+|^)WakeOnLan=.*$"
        insertafter: '^\[Link\]$'
        state: present
      when: item.disable_wol
      loop: "{{ _interface_links }}"
      become: yes
      notify:
        - reload systemd

    - name: Remove disable wake on lan line for others
      lineinfile:
        dest: "{{ item.file }}"
        backup: yes
        regexp: "(^#+|^)WakeOnLan=.*$"
        state: absent
      when: not item.disable_wol
      loop: "{{ _interface_links }}"
      become: yes
      notify:
        - reload systemd

- block:
    - name: Copy Network Manager configs
      copy:
        src: "{{ item }}"
        dest: '/etc/NetworkManager/conf.d'
      become: yes
      with_fileglob:
        - "files/NetworkManager/*"
