---

- block:
    - name: Define interfaces
      set_fact:
        _interface_links: >
          {{  [ { 'interface'   : item
                , 'file'        : '/etc/systemd/network/50-' + item + '.link'
                , 'disable_wol' : disable_wol and item[0:2] == 'en'
                } | combine(interface_links[item] | default({}))
              ] + _interface_links
          }}
      when: ansible_facts[item]['macaddress'] is defined
      loop: "{{ ansible_facts['interfaces'] }}"
    - name: Show interfaces
      debug:
        var: _interface_links

- block:
    # Template expects variable `interface` containing interface name.
    - name: Generate per-interface link file based on default.link
      template:
        src:  'interface.link'
        dest: "{{ item.file }}"
        force: no
        mode:   0644
        owner:  'root'
        group:  'root'
      vars:
        interface: "{{ item.interface }}"
      loop: "{{ _interface_links }}"
      become: yes
      notify:
        - reload systemd

    - name: Disable wake on lan
      lineinfile:
        dest: "{{ item.file }}"
        backup: yes
        line: 'WakeOnLan=off'
        regexp: "(^#+|^)WakeOnLan=.*$"
        insertafter: '^\[Link\]$'
        state: present
      when: item.disable_wol
      loop: "{{ _interface_links }}"
      become: yes
      notify:
        - reload systemd

