---
# tasks file for roles/sgf-system

- block:
    - name: Define interfaces
      set_fact:
        interface_links: >
          {{ [{ 'interface' : item
              , 'file'        : '/etc/systemd/network/50-' + item + '.link'
              }] + interface_links
          }}
      when: ansible_facts[item]['macaddress'] is defined
      loop: "{{ ansible_facts['interfaces'] }}"
    - name: Show interfaces
      debug:
        var: interface_links

- block:
    # Template expects variable `interface` containing interface name.
    - name: Generate per-interface link file based on default.link
      template:
        src:  'interface.link'
        dest: "{{ item.file }}"
        force: no
        mode:   0644
        owner:  'root'
        group:  'root'
      vars:
        interface: "{{ item.interface }}"
      loop: "{{ interface_links }}"
      become: yes
      notify:
        - reload systemd

    - name: Disable wake on lan
      lineinfile:
        dest: "{{ item.file }}"
        backup: yes
        line: 'WakeOnLan=off'
        regexp: "(^#+|^)WakeOnLan=.*$"
        insertafter: '^\[Link\]$'
        state: present
      loop: "{{ interface_links }}"
      become: yes
      notify:
        - reload systemd

