---
# tasks file for roles/sgf-system

- block:
    # Disable wake on lan on ethernet network interfaces. Their names should
    # start with `en` in new naming policy.
    # FIXME: Creating link file for interfaces effectively _disables_
    # `99-default.link` for that interface. That means, if i want to still
    # apply default link file, i should add its content there too..
    - name: Disable wake on lan on ehternet interface
      template:
        src:  "disable_wol.link"
        dest: "/etc/systemd/network/{{ '50-' + interface + '-disable_wol.link' }}"
      when: ansible_facts[interface]['macaddress'] is defined
            and interface[0:2] == 'en'
      loop: "{{ ansible_facts['interfaces'] }}"
      loop_control:
        loop_var: interface
      become: yes
      notify:
        - reload systemd
  when: disable_wol
