---
# tasks file for roles/sgf-system

- name: Set up network interfaces
  ansible.builtin.import_tasks: interfaces.yml
  tags:
    - 'network'

- block:
  - name: Copy RPZ for recursor
    ansible.builtin.copy:
      src: 'rpz.db'
      dest: "{{ rpz_dest }}"
      mode: 0644
      force: no
    notify: restart PowerDNS Recursor

  - name: Set RPZ permissions
    ansible.builtin.file:
      path: "{{ rpz_dest }}"
      mode: 0644

  become: yes
  tags:
    - 'pdns_recursor'

- name: Setup mounts
  ansible.builtin.import_tasks: mount.yml
  when: tmp_on_tmpfs
  tags:
    - 'mount'

- name: Configure apparmor
  ansible.builtin.import_tasks: apparmor.yml
  tags:
    - 'apparmor'

- name: Install grub functions
  ansible.builtin.import_tasks: grub.yml
  tags:
    - 'grub'

