---
# tasks file for roles/sgf-system

- name: Set up network interfaces
  import_tasks: interfaces.yml
  tags:
    - 'network'

- block:
  - name: Copy RPZ for recursor
    copy:
      src: 'rpz.db'
      dest: "{{ rpz_dest }}"
      mode: 644
      force: no
    notify: restart PowerDNS Recursor

  - name: Set RPZ permissions
    file:
      path: "{{ rpz_dest }}"
      mode: 0644

  become: yes

- block:
    - name: Mount tmpfs on /tmp
      mount:
        path:   /tmp
        src:    tmpfs
        fstype: tmpfs
        opts:   relatime,nodev,nosuid,noexec
        backup: yes
        state:  present
      notify:
        - reload systemd

  become: yes
  tags:
    - 'mount'

