---
# vars file for sgf-desktop

xmonad_bin: "{{ ansible_user_dir + '/bin/xmonad' }}"

ibus_dconf:
  - key: "general/use-system-keyboard-layout"
    value: "true"
  - key: "general/hotkey/triggers"
    value: "['<Control>space']"
  - key: "panel/use-custom-font"
    value: "true"
  - key: "panel/custom-font"
    value: "'DejaVu Serif 17'"

# Default desktop colors for initialize `colors` dictionary. Set `all_colors`
# to overwrite them all at once or set particular dictionary key to desired
# color in `colors` dictionary.
desktop_colors:
  xterm: 'disabled'

# List of build or runtime dependencies.
required_im_pkgs:
  - 'python-psutil'

xmonad_required_pkgs:
  - 'make'
  - 'libgmp-dev'
  - 'libx11-dev'
  - 'libxrandr-dev'
  - 'libxft-dev'
  - 'libxinerama-dev'
  - 'libxpm-dev'
  - 'libiw-dev'
  - 'trayer'
  - 'feh'
  - 'xterm'
  - 'gmrun'
  - 'xdotool'

desktop_required_pkgs:
  - 'xserver-xorg'
  - 'xinit'
  - 'x11-xserver-utils'

# List of packages to install.
install_im_pkgs: []
xmonad_install_pkgs: []
desktop_install_pkgs: []

haskell_stack_installer: "{{ ansible_user_dir + '/install_stack.sh' }}"
haskell_stack_bin_path: "{{ ansible_user_dir + '/bin' }}"

# Where system .desktop files are stored.
system_desktop_entries: '/usr/share/applications'

# Where to store local to user .desktop files.
user_desktop_entries: "{{ ansible_user_dir + '/.local/share/applications' }}"

# List of system and user firefox .desktop files found.
firefox_desktop_files: []

# Path to firfox `profiles.ini` .
firefox_profiles_ini: "{{ ansible_user_dir + '/.mozilla/firefox/profiles.ini' }}"

# URL where to download firefox 52 ESR.
firefox52esr_url: >
  {{ 'https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/linux-x86_64/'
        + firefox52esr_lang | replace('_', '-')
        + '/firefox-52.9.0esr.tar.bz2'
  }}
firefox52esr_bin: "{{ firefox52esr_dir + '/firefox/firefox' }}"

