---
# vars file for roles/sgf-system

# Value of global `notebook` variable for use in this role (with default, if
# nothing).
_sys_notebook: "{{ notebook | default(false) }}"

# Internal structure for storing interface information. Note, that unlike
# `interface_links` this is a _list_, not a dictionary.
_interface_links: []

# DNS Resonse policy zone (RPZ) file.
rpz_dest: '/etc/powerdns/rpz.db'

# `pdns_recursor-ansible` role variables.
pdns_rec_config_lua_file_content: >
  rpzFile("{{ rpz_dest }}", {})

pdns_rec_config:
  allow-from:
    - "127.0.0.1/8"
  local-address:
    - "127.0.0.1"
  pdns-distributes-queries: false
  reuseport: true
  forward-zones-recurse: >
    {{ dns_forwarder is defined | ternary('.=' + dns_forwarder | default(omit), none) }}
