---

# Convert default boolean values to bool. When default variable value
# specified on cmd with '-e' option, it's type will be string, not bool. And,
# hence, both 'false' and 'true' will be true (as bool), because string is not
# null.  And i need to convert them to bool explicitly either when i use them,
# or here.
_enable_tmux: "{{ enable_tmux | bool }}"
_enable_vim: "{{ enable_vim | bool }}"
_enable_keychain: "{{ enable_keychain | bool }}"
_dont_fuck_with_me: "{{ dont_fuck_with_me | bool }}"
_obtain_cowpowers: "{{ obtain_cowpowers | bool }}"

_force_overwrite: "{{ force_overwrite | bool }}"
_internet_available: "{{ internet_available | bool }}"

_vim_disable_arrow_keys: "{{ vim_disable_arrow_keys | bool }}"
_vim_plugins_enable: "{{ vim_plugins_enable | bool }}"

vim_dir:  "{{ ansible_user_dir + '/.vim' }}"
vim_package_dir:  "{{ vim_dir + '/bundle' }}"

tmux_plugin_dir: "{{ ansible_user_dir + '/.tmux/plugins' }}"
tmux_conf:  "{{ ansible_user_dir + '/.tmux.conf' }}"

keychain_bin: "{{ user_local_path + '/bin/keychain' }}"
keychain_deps:
  - 'make'

thefuck_bin: "{{ user_local_path + '/bin/thefuck' }}"
thefuck_deps:
  - 'python3-dev'
  - 'python3-pip'
  - 'python3-setuptools'

cowsay_deps:
  - 'cowsay'
  - 'lolcat'

# Url to download latest neo cowsay release info in json.
neo_cowsay_assets_url: 'https://api.github.com/repos/Code-Hex/Neo-cowsay/releases/latest'
# Where to save it.
neo_cowsay_assets_json: "{{ user_dist_dir + '/neo_cowsay_assets.json' }}"
# Loaded json will be here.
neo_cowsay_assets: []
# Url to download latest neo-cowsay archive. Will be determined automatically
# from corresponding github asset.
neo_cowsay_url: ''
# Name of latest neo-cowsay archive. Will be determined automatically from
# corresponding github asset.
neo_cowsay_archive: ''
neo_cowsay_dir: "{{ user_dist_dir + '/neo_cowsay' }}"

# Default console colors for initialize `colors` dictionary. Set `all_colors`
# to overwrite them all at once or set particular dictionary key to desired
# color in `colors` dictionary.
console_colors:
  vim:  'disabled'
  tmux: 'disabled'

user_man1_path: "{{ user_local_path + '/share/man/man1' }}"
# User's local bin under ~/.local directory tree.
user_local_bin: "{{ user_local_path + '/bin' }}"

# User's bin in ~/bin .
user_bin: "{{ ansible_user_dir + '/bin' }}"

# vim:
