---

vim_dir:  "{{ ansible_user_dir + '/.vim' }}"
vim_package_dir:  "{{ vim_dir + '/bundle' }}"

tmux_plugin_dir: "{{ ansible_user_dir + '/.tmux/plugins' }}"
tmux_conf:  "{{ ansible_user_dir + '/.tmux.conf' }}"

keychain_bin: "{{ user_local_path + '/bin/keychain' }}"
keychain_deps:
  - 'make'

thefuck_bin: "{{ user_local_path + '/bin/thefuck' }}"
thefuck_deps:
  - 'python3-dev'
  - 'python3-pip'
  - 'python3-setuptools'

pass_bin: "{{ user_local_path + '/bin/pass' }}"

# Default console colors for initialize `colors` dictionary. Set `all_colors`
# to overwrite them all at once or set particular dictionary key to desired
# color in `colors` dictionary.
console_colors:
  vim:  'disabled'
  tmux: 'disabled'

# User man1 directory. Locally installed programs will most likely install own
# man there.
user_man1_path: "{{ user_local_path + '/share/man/man1' }}"
# User's local bin under ~/.local directory tree.
user_local_bin: "{{ user_local_path + '/bin' }}"

# User's bin in ~/bin .
user_bin: "{{ ansible_user_dir + '/bin' }}"

# User bash_completion file. It's sourced at the end of main
# '/etc/bash_completion' .
user_bash_completion: "{{ ansible_user_dir + '/.bash_completion' }}"
# User bash completion directory. Locally installed programs will most likely
# put own completion files there.
user_bash_completion_dir: "{{ ansible_user_dir + '/.local/share/bash-completion/completions' }}"

# vim:
