---

# This role requires `sudo` to work without password. I.e. if role is running
# on remote server, i need to add something, like
#
#   user     ALL=(root:root) NOPASSWD: ALL
#
# to `/etc/sudoers`.
- block:
    # `python-apt` required for `apt` and `package_facts` ansible modules.
    - name:
      ansible.builtin.dpkg_selections:
        name: "{{ python_apt }}"
        selection: 'install'
      check_mode: true
      register: python_apt_status

    - name: Show python-apt info
      ansible.builtin.debug:
        msg: >-
          {{ "Package '" + python_apt + "' has dpkg status " + python_apt_status | string }}

    - name: Install python-apt package
      ansible.builtin.apt:
        name: "{{ python_apt }}"
        state: present
      when: python_apt_status.changed
      become: yes

    - name: Obtain package status
      ansible.builtin.package_facts:
      no_log: true

  tags:
    - 'apt'

