---

tmux_prefix: 'C-b'
vim_plugins:
  - repo: 'https://github.com/altercation/vim-colors-solarized.git'
  - repo: 'https://github.com/tpope/vim-fugitive.git'
  - repo: 'https://github.com/plasticboy/vim-markdown.git'
  - repo: 'https://github.com/tpope/vim-sensible.git'
  - repo: 'https://github.com/dhruvasagar/vim-table-mode.git'

