---

tmux_prefix: 'C-b'
tmux_prefix_key: "{{ tmux_prefix }}"

vim_plugins:
  - repo: 'https://github.com/altercation/vim-colors-solarized.git'
  - repo: 'https://github.com/tpope/vim-fugitive.git'
  - repo: 'https://github.com/plasticboy/vim-markdown.git'
  - repo: 'https://github.com/tpope/vim-sensible.git'
  - repo: 'https://github.com/dhruvasagar/vim-table-mode.git'

vim_disable_arrow_keys: true

# This dictionary is used by several roles (e.g. `sgf-console` and
# `sgf-desktop`). This role initializes only part of its keys from
# `console_colors` dictionary. To overwrite particular keys, set them in
# parent task.
colors: {}

# Default for _all_ `colors` dictionary keys (overwriting role default value).
# But particular `colors` key set explicitly in parent task will overwrite
# this value. This variable used by several roles (e.g. `sgf-console` and
# `sgf-desktop`).
# all_colors: 'disabled'
