---

xkb_mods: true
xkb_clear_options: true

user_xkb_dir: "{{ ansible_user_dir + '/.xkb/' }}"
user_xkb_rules: "{{ user_xkb_dir + 'rules/evdev.sgf' }}"

user_x_resources: "{{ ansible_user_dir + '/.Xresources.d' }}"

im_enabled: true

xmonad_branch: master

user_opt_dir: "{{ ansible_user_dir + '/opt' }}"

# Language of firefox 52.9.0esr to use.
firefox52esr_lang: 'en_US'
# Directory, where to unpack firefox ESR 52.
firefox52esr_dir: "{{ user_opt_dir + '/firefox-52esr' }}"
# Profile name to use with firefox ESR 52.
firefox52esr_profile: 'default-52esr'
# Profile name to use with system default firefox.
firefoxDefault_profile: 'default'

# Overwrite files normally left untoched. Set this only _once_ for overwriting
# previous possible incorrect configuration, because setting this permanently
# will result in _always changed_ status of playbook run.
force_overwrite: no

# This dictionary is used by several roles (e.g. `sgf-console` and
# `sgf-desktop`). This role initializes only part of its keys from
# `desktop_colors` dictionary. To overwrite particular keys, set them in
# parent task.
colors: {}

# Default for _all_ `colors` dictionary keys (overwriting role default value).
# But particular `colors` key set explicitly in parent task will overwrite
# this value. This variable used by several roles (e.g. `sgf-console` and
# `sgf-desktop`).
# all_colors: 'disabled'
