---

xkb_mods: true
xkb_clear_options: true

user_xkb_dir: "{{ ansible_user_dir + '/.xkb/' }}"
user_xkb_rules: "{{ user_xkb_dir + 'rules/evdev.sgf' }}"

user_x_resources: "{{ ansible_user_dir + '/.Xresources.d' }}"

im_enabled: true

xmonad_branch: master
xmobar_branch: master
xmonad_repo_dir: "{{ ansible_user_dir + '/sgf-xmonad-config' }}"

user_opt_dir: "{{ ansible_user_dir + '/opt' }}"

# System firefox .desktop entry names (which to overwrite). Note, that i
# should overwrite _all_ entries, otherwise ones left intact may break
# profile.
firefox_desktop_names:
  - 'firefox.desktop'
  - 'firefox-esr.desktop'
  - 'iceweasel.desktop'
# FIXME: Rename to 'firefox-system-profile'
# Profile name to hardcode into .desktop files launching _system_ firefox.
firefox_system_profile: 'default'
# Which firefox to use as default browser (default mime handler for urls,
# etc).
firefox_default_desktop: 'firefox-52esr.desktop'

# Firefox versions to install.
#   - 'name' is unique name (either 'name' or 'version' is required). It's
#   used as id string in various places (see below).
#   - 'version' is firefox version to install (either 'name' or 'version' is
#   required). It's used to construct 'url' and 'comment' fields, if either
#   one is omitted, and as id string in various places (see below). See
#   https://ftp.mozilla.org/pub/firefox/releases/ for a list of valid
#   versions. Also, word 'latest' is recognized.
#   - 'lang' is firefox language to install. Languages here are _not_ locale
#   language codes. E.g. for russian version, i should just use `ru`. Check
#   the https://ftp.mozilla.org/pub/firefox/releases/ download link to ensure
#   the code is correct. Language and country separator may be '_' or '-'.
#   It's also used as id string (see below).
#   - 'url' (optional) is download url. If omitted, 'url' will be constructed
#   depending on 'version' and 'lang' fields.
#   - 'profile' (optional) is profile name to hardcode into firefox's .desktop
#   file . If omitted, it'll be derived from 'version' or 'name' (see below).
#   - 'comment' (optional) is description used in desktop entry in 'Comment'
#   and 'X-GNOME-FullName' fields. If omitted, comment will be derived from
#   'version'.
#
# Firefox dictionary element id string is constructed from 'version' (if not
# defined, 'name' is used instead) and (sometimes) 'lang' fields and used to
# derive archive name, install (unpack) directory name, binary name (symlink
# in user's ~/bin), desktop file and default profile names, etc.
firefox2: []

# Overwrite files normally left untoched. Set this only _once_ for overwriting
# previous possible incorrect configuration, because setting this permanently
# will result in _always changed_ status of playbook run.
force_overwrite: no

# This dictionary is used by several roles (e.g. `sgf-console` and
# `sgf-desktop`). This role initializes only part of its keys from
# `desktop_colors` dictionary. To overwrite particular keys, set them in
# parent task.
colors: {}

# Default for _all_ `colors` dictionary keys (overwriting role default value).
# But particular `colors` key set explicitly in parent task will overwrite
# this value. This variable used by several roles (e.g. `sgf-console` and
# `sgf-desktop`).
# all_colors: 'disabled'

# Directory where to download and save locally installed programs and files.
user_dist_dir: "{{ ansible_user_dir + '/opt/dist' }}"
