---

xkb_mods: true
xkb_clear_options: true

user_xkb_dir: "{{ ansible_user_dir + '/.xkb/' }}"
user_xkb_rules: "{{ user_xkb_dir + 'rules/evdev.sgf' }}"

user_x_resources: "{{ ansible_user_dir + '/.Xresources.d' }}"

im_enabled: true

# See templates/Xresources/solarized.res for allowed values. Or any other
# value to disable.
xterm_solarized: 'dark'

xmonad_branch: master
